\input texinfo
@c %**start of header
@setfilename serveez.info
@settitle Serveez-MG Documentation
@c %** end of header

@include version.texi


@copying
This manual is for Serveez-MG @value{VERSION}.

Copyright @copyright{} 2010 Michael Gran <spk121@@yahoo.com>@*
Copyright @copyright{} 2000, 2001, 2002 Stefan Jahn <stefan@@lkcc.org>@*
Copyright @copyright{} 2000, 2001, 2002 Raimund Jacob <raimi@@lkcc.org>@*
Copyright @copyright{} 1999 Martin Grabmueller <mgrabmue@@cs.tu-berlin.de>@*

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1
or any later version published by the Free Software Foundation.
A copy of the license is included in the section entitled "GNU
Free Documentation License".
@end quotation
@end copying

@titlepage
@title Serveez-MG, version @value{VERSION}
@subtitle A Guile-friendly server framework
@subtitle Edition @value{EDITION},  @value{UPDATED}
@author Michael Gran
@author Stefan Jahn
@author Raimund Jacob

@page
@vskip 0pt plus 1filll
@insertcopying

@end titlepage

@contents

@ifnottex
@node Top, Introduction, (dir), (dir)
@top Serveez-MG

This manual is for Serveez-MG, version @value{VERSION}
@end ifnottex

@menu
* Introduction::                
* Using Serveez::               
* Concept::                     
* Server::                      
* Coserver::                    
* Bibliography::                 
* License::                     

@detailmenu
 --- The Detailed Node Listing ---

Configuring Serveez

* Define ports::                Port configuration definition
* Define servers::              Server definition
* Bind servers to ports::       How to bind servers to port configurations

Server

* Introduction to servers::     Protocol servers in Serveez
* Writing servers::             How to write Internet protocol servers
* Configuring servers::         How do I configure an existing server ?
* Existing servers::            Which kind of servers do we have already ?

Writing servers

* Guile servers::               Servers using Serveez's guile interface

Existing servers

* HTTP Server::                 Integrated Web Server description
* Control Protocol Server::     Serveez control center
* Passthrough Server::          Description of the program passthrough server
* Mandel Server::               Distributed Mandelbrot server

Coserver

* What are coservers::          The use of coservers in Serveez
* Existing coservers::          What kind of coservers already exist ?

@end detailmenu
@end menu

@node Introduction, Using Serveez, Top, Top
@chapter Introduction

There once was a great server framework named GNU Serveez.  It
provided routines and help for implementing IP based servers
(currently TCP, UDP and ICMP).  And it was amazing.  In its library
were routines that worked on dozens of platforms, and it was a great
platform for writing your own webservice.

The code for it is still around, of course, on the GNU website, but,
the project appears to be dead, or mostly dead anyway.

Anyone that decided to pick up and update GNU Serveez would have a
hell of a task: with all those many operating systems laboriously
supported and with all those special cases for various libraries,it
would be a trial just to keep it from bitrotting.  It might actually
be impossible to keep it up to date without a huge community behind
it.  But it never really got that huge community it needed.

When I, Mike Gran, wanted to make a Guile webservice, I decided to
dust Serveez off and make it work for me, on my one specific
platform.  Serveez has built-in support for the Guile dialect of
Scheme, which makes it rather unique.

For now I call it ``Serveez-MG'' because the code is mostly GNU
Serveez, but, this is really a fork of the true GNU Serveez.  Don't
confuse the two.  This port is targeted to only work on my machines,
and it only implements a handful of the servers that GNU Serveez does.
As a one person project, I needed to strip it down to something I
could understand. 

@node Using Serveez, Concept, Introduction, Top
@chapter Using Serveez

We know, you usually don't read the documentation.  Who does.  But
please, read at the very least this chapter.  It contains information on
the basic concepts.  Larger parts of the manual can be used as a
reference manual for the various servers.

@section Building and installing

@subsection Rebuild the package from the sources
You can skip this section if you are familiar with the GNU'ish way of 
configuring, compiling and installing a GNU package.

@subsubsection Getting the source
Serveez-MG can be found on
@uref{http://github.com/spk121/serveez-mg}.  It might just be in a Git
repo, or there might be a download in the Download's directory.

@subsubsection Requirements
Serveez needs GNU Guile 2.0 or later.  Guile itself has many
dependencies, so beware.

@subsubsection Installation
If you're building this from the source code, then you will find a
file named 'INSTALL' in the source code package.  It has helpful
information on getting Serveez-MG to compile.  But, compiling from
source is a trial for the unfamiliar.  Maybe someday some GNU or Linux
distribution will package this, but, probably not.

@section Starting Serveez

When Serveez-MG is started it reads its configuration from a file
called @file{serveez.cfg} in the current directory and runs the server
loop afterwards. Press @key{^C} to abort the execution of this
program.  Serveez-MG is not interactive and does not automatically
detach from the terminal.

@section Command line options

@table @code
@item -h, --help
Display this help and exit.
@item -V, --version
Display version information and exit.
@item -i, --iflist
List local network interfaces and exit.
@item -f, --cfg-file=FILENAME
File to use as configuration file (serveez.cfg).
@item -v, --verbose=LEVEL
Set level of logging verbosity.
@item -l, --log-file=FILENAME
Use @code{FILENAME} for logging (default is stderr).
@item -P, --password=STRING
Set the password for control connections.
@item -m, --max-sockets=COUNT
Set the maximum number of socket descriptors.
@item -d, --daemon
Start as daemon in background.
@item -c, --stdin
Use standard input as configuration file.
@end table

@section Configuring Serveez

As noted above Serveez is configured via a configuration file which is
by default @file{serveez.cfg} and can be set by passing the @samp{-f}
command line argument.  When you pipe a file into Serveez or pass the
@samp{-c} argument on the command line the input stream will be used
as configuration file no matter whether you passed a @samp{-f} command
line switch or not.

To make configuring more fun we did not invent yet another configuration 
file format.  Instead we use a dialect of the Scheme programming language 
called GNU Guile (@uref{http://www.gnu.org/software/guile/}).  There is no 
need to be worried if you are not a programmer.  What you have to do is 
really simple and this document shows you everything you need to know.  We 
also provide many examples.  However there are some simple concepts you 
have to understand.  The following paragraphs will explain them.

The idea of the configuration file is this: Serveez starts, runs the 
configuration file (other applications usually just read them and remember 
the settings) and finally enters its main loop doing the things you wanted 
it to.

There are three things you have to do in the configuration file.

@menu
* Define ports::                Port configuration definition
* Define servers::              Server definition
* Bind servers to ports::       How to bind servers to port configurations
@end menu

@node Define ports, Define servers, Using Serveez, Using Serveez
@subsection Define ports

A @code{port} (in Serveez) is a transport endpoint. You might know them
from other TCP or UDP server applications. For example: web servers
(HTTP) usually listen on TCP port 80. However, there is more than TCP
ports: we have UDP, ICMP and named pipes each with different options to
set. Every port has a unique name you assign to it. The name of the port is
later used to bind servers to it.

The following examples show how you setup different types of port 
configurations. You start to define such a port using the Guile function
@code{(define-port!)}. The first argument to this functions specifies the
name of the port configuration. The remaining argument describes the
port in detail.

@subsubsection Port configuration items
This table describes each configuration item for a port in Serveez.  Note 
that not each item applies to every kind of port configuration.

@table @code
@item proto (string)
This is the main configuration item for a port configuration setting up the
type of port.  Valid values are @samp{tcp}, @samp{udp}, @samp{icmp}, 
@samp{raw} and @samp{pipe}.  This configuration item decides which of the 
remaining configuration items apply and which do not.

@item port (integer in the range 0..65535)
The @code{port} item determines the network port number on which TCP and UDP
servers will listen.  Thus it does not make sense for ICMP and named pipes.
If you pass @samp{0} Serveez will determine a free port in the range 
between 1 and 65535.

@item recv (string or associative list)
This item describes the receiving (listening) end of a named pipe
connection, i.e. the filename of a fifo node to which a client can
connect by opening it for writing.  Both the @code{recv} and @code{send}
item apply to named pipes only.  The value can either be an associative
list or a simple filename. Using a simple filename leaves additional
options to use default values. They deal mainly with file permissions
and are described below.

@item send (string or associative list)
This item is the sending end of a named pipe connection. It is used to
send data when the receiving (listening) end has detected a connection.
The following table enumerates the additional options you can
setup if you pass an associative list and not a simple filename.

@table @code
@item name (string)
The filename of the named pipe.

@item permission (octal integer)
This specifies the file permissions a named pipe should be created with.
The given number is interpreted in a Unix'ish style (e.g. @samp{#o0666}
is a permission field for reading and writing for the creating user, all
users in the same group and all other users).

@item user (string)
The file owner (username) of the named pipe in textual form.

@item group (string)
The file owner group (groupname) of the named pipe in textual form.  If
this item is left it defaults to the file owner's primary group.

@item uid (integer)
The file owner of the named pipe as a user id.  You are meant to specify
either the @code{uid} item or the @code{user} item.  Serveez will
complain about conflicting values.

@item gid (integer)
The file owner group of the named pipe as a group id.  This item
defaults to the file owner's primary group id.  You are meant to specify
either the @code{gid} item or the @code{group} item.  Serveez will croak
about conflicting values.
@end table

@item ipaddr (string)
This configuration item specifies the IP address (either in dotted decimal
form e.g. @samp{192.168.2.1} or as a device description which can be
obtained via @samp{serveez -i}) to which a server is bound to.  The 
@samp{*} keyword for all known IP addresses and the @samp{any} keyword for 
any IP address are also valid values.  The default value is @samp{*}.  The
configuration item applies to network ports (TCP, UDP and ICMP) only.

@item device (string)
The @code{device} configuration item also refers to the IP address a server
can be bound to.  It overrides the @code{ipaddr} item.  Valid values are
network device descriptions (probably no aliases and no loopback devices).
It applies to network ports (TCP, UDP and ICMP) only.

@item backlog (integer)
The @code{backlog} parameter defines the maximum length the queue of 
pending connections may grow to.  If a connection request arrives with the 
queue full the client may receive an error.  This parameter applies to
TCP ports only.

@item type (integer in the range 0..255)
This item applies to ICMP ports only.  It defines the message type 
identifier used to send ICMP packets (e.g. @samp{8} is an echo message 
i.e. PING).

@item send-buffer-size (integer)
The @code{send-buffer-size} configuration item defines the maximum number 
of bytes the send queue of a client is allowed to grow to.  The item 
influences the "send buffer overrun error condition".  For packet oriented
protocols (UDP and ICMP) you need to specify at least the maximum number
of bytes a single packets can have.  For UDP and ICMP this is 64 KByte.
The value specified here is an initial value. It is used unless the
server bound to this port changes it.

@item recv-buffer-size (integer)
The @code{recv-buffer-size} configuration item defines the maximum
number of bytes the receive queue of a client is allowed to grow to.
The item influences the "receive buffer underrun error condition".  The
value specified here is an initial value. It is used unless the server
bound to this port changes it.

@item connect-frequency (integer)
This item determines the maximum number of connections per second the port 
will accept.  It is a kind of "hammer protection".  The item is evaluated
for each remote client machine separately.  It applies to TCP ports.

@item allow (list of strings)
Both the @code{allow} and @code{deny} lists are lists of IP addresses in 
dotted decimal form (e.g. @samp{192.168.2.1}). The @code{allow} list defines
the remote machines which are allowed to connect to the port.  It applies
to TCP ports.

@item deny (list of strings)
The @code{deny} list defines the remote machines which are not allowed to 
connect to the port.  Each connection from one of these IP addresses will
be refused and shut down immediately.  It applies to TCP ports.
@end table

@subsubsection TCP port definition
Definition of a TCP port configuration with the name "foo-tcp-port". The
enhanced settings are all optional including the @var{ipaddr} property
which defaults to @samp{*}. The @var{ipaddr} item can contain any form
of a dotted decimal internet address, a @samp{*}, @samp{any} or an
interface description which you can obtain by running @samp{serveez -i}.

@example
(define-port! 'foo-tcp-port '(
    ;; usual settings
    (proto  . tcp)              ;; protocol is tcp
    (port   . 42421)            ;; network port 42421
    (ipaddr . *)                ;; bind to all known interfaces
    (device . eth0)             ;; bind to network card

    ;; enhanced settings
    (backlog           . 5)     ;; enqueue max. 5 connections
    (connect-frequency . 1)     ;; allow 1 connect per second
    (send-buffer-size  . 1024)  ;; initial send buffer size in bytes
    (recv-buffer-size  . 1024)  ;; initial receive buffer size in bytes

    ;; allow connections from these ip addresses
    (allow             . (127.0.0.1 127.0.0.2))

    ;; refuse connections from this ip address
    (deny              . (192.168.2.7))
  ))
@end example

@subsubsection Pipe port definition
Definition of a pipe port configuration with the name "foo-pipe-port".
When bound to a server it creates the receiving end and listens on that.
If some client accesses this named pipe the server opens the sending end
which the client has to open for reading previously.

The only mandatory item is the file name of each pipe.  If you want to
specify a user creating the named pipe (file ownership) use either the
@var{user} or the @var{uid} setting.  Same goes for the items
@var{group} and @var{gid}.

@example
(define-port! 'foo-pipe-port `(
    (proto . pipe)                   ;; protocol is named pipe

    ;; specify the receiving endpoint    
    (recv . ((name . ".foo-recv")    ;; name of the pipe
             (permissions . #o0666)  ;; create it with these permissions
             (user . "calvin")       ;; as user "calvin"
             (uid . 50)              ;; with the user id 50
             (group . "heros")       ;; which is in the group "heros"
             (gid . 100)))           ;; with the group id 100

    ;; specify the sending endpoint
    (send . ((name . ".foo-send")
             (permissions . #o0666)
             (user . "hobbes")
             (uid . 51)
             (group . "stuffed")
             (gid . 101)))
   ))
@end example

@subsubsection UDP port definition
Simple definition of a UDP port configuration with the name "foo-udp-port".

@example
(define-port! 'foo-udp-port `((proto . udp)
                              (port  . 27952)))
@end example

@node Define servers, Bind servers to ports, Define ports, Using Serveez
@subsection Define servers

A @code{server} (in Serveez) is a snippet of code that implements some
protocol. There are a few servers built into Serveez but you can implement
your own, too. For example we provide a webserver implementing the
Hypertext Transfer Protocol (HTTP). Each server has a different set of
options you can change. You can have many instances of every server, each
with a different set of options. For example: You can create a webserver
on TCP port 42420 publishing the Serveez documentation and also have another
webserver on a different port publishing something else. Every server
has a unique name you assign to it. The name of the server is later used
to bind it to a port.

The following example instantiates a server with the short name "foo". Each
server in Serveez has got a short name. @xref{Existing servers}, for the 
details. This example demonstrates everything which is possible in server
configurations. You start a definition of a server with the guile function 
@code{(define-server!)}. The following argument specifies the name of the
server instance (in this case "foo-server") which starts with the short 
name. The second argument describes the server in detail. Each 
configuration item is setup with a @code{(key . value)} pair where "key" is
the name of the configuration item and "value" is the value which depends
on the type of the item. @xref{Configuring servers}, for a detailed 
description of each type of value.

@example
(define-server! 'foo-server '(
    (bar . 100)                             ;; number
    (reply . "Booo")                        ;; character string
    (messages .                             ;; list of strings
      ("Welcome to the foo test server."
       "This one echos your lines."))
    (ports . (5 6 7 8 9))                   ;; list of numbers
    (port . foo-tcp-port)                   ;; a port configuration
    (assoc . (( "GNU" . "great" )           ;; associative list
              ( "Tree" . "tall" )))
    (truth . #f)                            ;; boolean value
  ))
@end example

Serveez provides a number of server types. Each of them has a short name.
The name of the server instance has to begin with this short name followed
by a dash (-). You can append any suffix then. In the example above "foo" 
is the short name and "foo-server" the name of the server instance.

@node Bind servers to ports,  , Define servers, Using Serveez
@subsection Bind servers to ports

Finally you can bind servers to ports. When you do so the server you
created listens on the port, accepts connections and serves clients. It
does so as soon as Serveez enters its main loop right after running the
configuration file. Serveez won't stop until you interrupt it (e.g. by
pressing @key{^C} in the terminal you started it in).

This example binds the server "foo-server" (s.a.) to the port "foo-tcp-port"
which was described above. Therefore you need to call the guile function
@code{(bind-server!)} which takes two arguments specifying the name of a port 
configuration and a server instance. Both need to be defined before
you can write this statement.

@example
(bind-server! 'foo-tcp-port 'foo-server)
@end example

One of the main features of Serveez is that you can bind multiple
servers to the same port. This for example is useful to pass braindead
firewall configurations or proxy servers. It is also possible to bind
servers to ports they are actually not designed for. This might be used
for debugging servers or other funny things (again, think about the
firewall). This is the point we have to warn you: Some protocols cannot
share the same port (e.g. the tunnel server) and some protocols simply won't
work on 'wrong' ports. Additionally, you will not get error messages when
that happens. The server just will not work then.

@subsection Additional configuration possibilities

The three functions @code{(define-port!)}, @code{(define-server!)} and 
@code{(bind-server!)} return @code{#t} on success and @code{#f} on failure.
For your convenience we provide some more Guile functions.  Some of these
are based upon the above.  You will find the additional functions in the
file @file{serveez.scm}.  In order to include this convenience 
functionality you can @code{(primitive-load "serveez.scm")} at the top
of the configuration file.

@table @code
@item (interface-add! . interface)
Add one more network interface to the list of known interfaces. You can get
the list of known interfaces by running @samp{serveez -i}. The @var{interface}
argument must be in dotted decimal form (e.g. 127.0.0.1). Serveez provides
this function for systems where it is unable to detect the list of network
interface automatically.

@c @item (loadpath-add! . path)
@c Extends the load path for server modules by the path name @var{path}.

@item (bind-servers! . args)
This function is based upon @code{(bind-server!)}. It takes a list of port
configurations and servers and binds each to another.

@item (bind-tcp-port-range! from to . servers)
Bind the list of @var{servers} to simple TCP port configurations whose network
ports range between @var{from} and @var{to} both inclusive.

@item (bind-udp-port-range! from to . servers)
Bind the list of @var{servers} to simple UDP port configurations whose network
ports range between @var{from} and @var{to} both inclusive.

@item (serveez-verbosity verbosity)
Set the core library's logging verbosity to the @var{verbosity} level. Lesser
values mean fewer logging messages. This settings gets overridden by command
line.

@item (serveez-maxsockets max)
Set the number of maximum socket descriptors (number of concurrent 
connections). When passing Serveez the -m command line argument this setting
gets overridden, too.

@item (serveez-passwd password)
Set the @var{password} for the control protocol.
@end table

We now have a closer look at the internals of Serveez. If you
are not interested in that have a look at the existing
servers (@xref{Existing servers}.).

@node Concept, Server, Using Serveez, Top
@chapter Concept

@section Overall concept
The primary functionality Serveez provides is a framework for Internet
services.  It can act as a kind of server collection and may even
replace super-servers such as the inetd daemon.

Its key features and benefits are:

@itemize @bullet
@item support for packet and connection oriented protocols@*
Serveez currently supports two server types.  TCP and named pipe servers
are connection oriented servers.  This type of server accepts a client's
connection request and communicates with it using a dedicated
connection.  The format of the incoming and outgoing data streams are
irrelevant to Serveez.  Packet oriented servers (like UDP and ICMP)
receive data packets and respond to the sender with data packets.  A
server in Serveez can detect whether it is bound to a packet or
connection oriented port configuration and thus can act as the expected
type.

@item server and client functionality@*
Besides a wide variety of server capabilities, Serveez also contains
some client functionality.  This may be necessary when a server is meant
to establish a connection to another server in response to an incoming
request.  For example, imagine a protocol where a client tells the
server "Let me be the server.  Please connect to this @var{host} at this
@var{port}.".  You are also able to implement pure clients.

@item complete lack of platform portability@*
The original GNU Serveez was a miracle of platform portability.  This
version, Serveez-MG, is not.  It very specifically targets those
GNU/Linux distributions that are complient with the LSB 4.1
specification.

@item powerful configuration capabilities@*
Server configuration has always been a complicated but very important
issue.  When Serveez starts up it runs the configuration file using the
programming language Guile.  In contradiction, other (server)
applications just read their configuration files and remember the
settings in it.  This makes them powerful enough to adapt the Serveez
settings dynamically.  Using the Guile interpreter also means that you
can split your configuration into separate files and load these, perhaps
conditionally, from the main configuration file.

@item easy server implementation@*
Serveez is a server framework.  When implementing a new server the
programmer need pay little or no attention to the networking code but is
free to direct his attention to the protocol the server is meant to
support.  That protocol may be an established one such as HTTP, or may
be a custom protocol fitting the specific application's requirements.
The @ref{Writing servers} section describes this process in detail.

@item code reusability@*
The GNU Serveez package did come along with a core library and an API
for the C language which contained most of the functionality necessary
to write an Internet server.  Most probably, a programmer could also
use the library for other (network programming related) purposes.
But, for this version, Serveez-MG, I've stripped out some of its
functionality, so the original GNU version might be better if you
actually wanted a core library.

This version does retain the Guile functionality, though.

@item server instantiation and network port sharing@*
Once you have written a protocol server and integrated into Serveez's
concept of servers the user can instantiate (multiply) the server.  At
the first glimpse this sounds silly, but with different server
configurations it does not.  If, for example, an administrator wishes to
run multiple HTTP servers with different document roots, Serveez will
handle them all in a single process.  Also if the same administrator
wants to run a HTTP server and some other server on the same network
port this is possible with Serveez.  You can run a single server on
different network ports, too.
@end itemize

@section I/O Strategy
Serveez-MG's I/O strategy is the traditional @code{poll()} function

@subsection Limits on open filehandles

The limits set by @code{ulimit()} or @code{setrlimit()} affect the
performance of the servers.

@node Server, Coserver, Concept, Top
@chapter Server

@menu
* Introduction to servers::     Protocol servers in Serveez
* Writing servers::             How to write Internet protocol servers
* Configuring servers::         How do I configure an existing server ?
* Existing servers::            Which kind of servers do we have already ?
@end menu

@node Introduction to servers, Writing servers, Server, Server
@section Introduction to servers

Serveez is a kind of server server. It allows different protocol
servers to listen on various TCP/UDP ports, on ICMP sockets and on named
pipes. Servers are instantiated with a certain configuration. It is
possible to run multiple different servers on the same port.

This chapter covers all questions about how to write your own Internet
protocol server with this package. Most of the common tasks of
such a server have got a generic solution (default routines) which could be 
"overridden" by your own routines. There are some examples within this 
package. They are showing the possibilities with this package and how to
implement servers.

The @samp{foo} server does not do anything at all and is of no actual use
but could be a basis for a new protocol server. We are now going to describe
how this specific server works. Eventually the reader might get an 
impression of what is going on.

For better understanding the text below we will use the following
terminology:
@table @asis

@item server definition
A server definition is a @code{#<svz-servertype>} which contains
server specific members like its name, different callbacks, a single
default configuration and a list of configuration items which
determines what can be configured.

@item server configuration
A server configuration can be any kind of structure. The default server
configuration must be specified within the server definition (see above).
When instantiating a server (which is done via the configuration file) the
configuration items specified in the server definition get processed and
are put into a copy of the default configuration. Thus we get an instance.

@item server instance
A server instance is a copy of the server definition including the modified
server configuration. A server gets instantiated by the configuration file
parser. The concept of server instances has been introduced because we 
wanted Serveez to have the following features. A single server can have
multiple instances with different behaviour due to different server
configurations. A server instance can be bound to multiple port
configurations. Different server instances (of the same and/or different
server type) can share the same port configuration.
@end table

@node Writing servers, Configuring servers, Introduction to servers, Server
@section Writing servers

Serveez is meant to be a server framework. That is why it supports various
ways to implement Internet servers. First of all there are some servers
already included in the main serveez package. (@xref{Existing servers}.)
These are called @samp{Builtin servers}. Another possibility to add a new
server are @samp{Embedded servers} which are shared libraries (or DLL's)
containing the server implementation. These can be dynamically loaded by
Serveez at runtime. This kind of server is also called @samp{Server modules}.
A third possibility are the @samp{Guile servers} which allow even
unexperienced schemers to write an Internet server.

This section describes each of the above possibilities in detail.

@menu
* Guile servers::               Servers using Serveez's guile interface
@end menu

@node Guile servers,  , Writing servers, Writing servers
@subsection Guile servers

@include guile-api.texi

@node Configuring servers, Existing servers, Writing servers, Server
@section Some words about server configuration

If you define a server you basically pass an instance name and a list of
items to the @code{(define-server!)} function. Each item has a name and a
value. A value has a type. We provide several types: integers (numbers),
integer arrays, strings, string arrays, booleans (yes/no-values), hashes
(associations) and port configurations.

The following table shows how each kind of value is set up in the 
configuration file. @var{item} is the name of the item to be configured.

@table @asis
@item Integer@*
Example: (item . 42)
@item Integer array@*
Example: (item . (0 1 2 3))
@item String@*
Example: (item . "a character string")
@item String array@*
Example: (item . ("abc" "cba" "bca" "acb"))
@item Boolean@*
A normal boolean in guile is represented by #t or #f. But the configuration
file parser additional understand some bare words and numbers.@*
Example: (item . #f)
@item Hash@*
Hash maps associate keys with values. Both must be character strings.@*
Example: (item . (key1 . "value1") (key2 . "value2"))
@item Port configuration@*
@xref{Define ports}, for more information on this. When configuring a port
configuration you need to define it via @code{(define-port!)} previously and
put its symbolic name into the configuration.@*
Example: (item . foo-tcp-port)
@end table

The next chapter describes the servers currently implemented using 
Serveez. The configuration items used by each of them are described in the 
following format:

@table @code
@item NameOfTheItem (Type, default: DefaultValue, Comments)
Description of the configuration item named @samp{NameOfTheItem} (case 
sensitive). @samp{Type} can be either @samp{integer}, @samp{integer array}, 
@samp{string}, @samp{string array}, @samp{boolean}, @samp{hash} or 
@samp{port configuration}. The @samp{Comments} is an optional text.
@end table

The example configuration file @file{data/serveez.cfg} contains an example 
definition of each server already implemented. You can copy and modify the 
example for an easy start.

@node Existing servers,  , Configuring servers, Server
@section Existing servers

@menu
* HTTP Server::                 Integrated Web Server description
* Control Protocol Server::     Serveez control center
* Passthrough Server::          Description of the program passthrough server
* Mandel Server::               Distributed Mandelbrot server
@end menu

@node HTTP Server, Control Protocol Server, Existing servers, Existing servers
@subsection HTTP Server

@subsubsection General description

The integrated HTTP server was originally meant to be a simple but fast
document server. But now it can even execute CGI scripts. The GET, HEAD and
POST methods are fully functional. Additionally Serveez produces 
directory listings when no standard document file 
(e.g. @file{index.html}) has been found at the requested document node
(directory).  Furthermore it implements a file cache for speeding up
repetitive HTTP request.


@subsubsection Configuration

The following options can be set from the configuration file.

@table @code
@item indexfile (string, default: index.html)
The @code{indexfile} parameter is the default file served by the HTTP 
server when the user does not specify a file but a document node
(e.g. @uref{http://www.lkcc.org/}).

@item docs (string, default: ../show)
The @code{docs} parameter is the document root where the server finds its
web documents.

@item userdir (string, default: public_html)
Each @samp{~user} request gets converted into the given users home
directory. The string will be appended to this directory. Its default
value is @samp{public_html}.

@item cgi-url (string, default: /cgi-bin)
This parameter is the first part of the URL the HTTP server identifies a
CGI request. For instance if you specify here @file{/cgi-bin} and the
user requests @uref{http://www.lkcc.org/cgi-bin/test.pl} then the
HTTP server tries to execute the program @file{test.pl} within the
@code{cgi-dir} (see below) and pipes its output to the user.

@item cgi-dir (string, default: ./cgibin)
The @code{cgi-dir} is the CGI document root (on the server).

@item cgi-application (hash, default: empty)
Within the MinGW32 and native port you can use this hash to associate
certain file suffices with applications on your computer (e.g. "pl" with
"perl"). This is necessary because there is no possibility to check whether
a file is executable on Win32.

@item cache-size (integer, default: 200 kb)
This specifies the size of the document cache in bytes for each cache
entry.

@item cache-entries (integer, default: 64)
This parameter specifies the maximum number of HTTP file cache entries
(files). When you instantiate more than one HTTP server the biggest value
wins. The HTTP file cache is shared by all HTTP servers.@*
@strong{Please note}: If your harddrive/filesystem combination proves to 
be faster than the HTTP file cache you should disable it by setting both
@code{cache-size} and @code{cache-entries} to zero.

@item timeout (integer, default: 15)
The @code{timeout} value is the amount of time in seconds after which 
a keep-alive connection (this is a HTTP/1.1 feature) will be closed when
it has been idle.

@item keepalive (integer, default: 10)
On one keep-alive connection can be served the number of @code{keepalive}
documents at all. Then the connection will be closed.
Both this and the @code{timeout} value are just to be on the safe side. 
They protect against idle and high traffic connections.

@item default-type (string, default: text/plain)
The @code{default-type} is the default content type the HTTP server
assumes if it can not identify a served file by the @code{types} hash
and the @code{type-file} (see below).

@item type-file (string, default: /etc/mime.types)
This should be a file like the @file{/etc/mime.types} on Unix systems.
It associates file suffices with MIME types.

@item types (hash, default: empty)
If you want to specify special content types do it here. This parameter
is a hash map associating file suffices with HTTP content types (MIME types).

@item admin (string, default: root@@localhost)
Your address, where problems with the server should be e-mailed.
This address appears on some server-generated pages, such as error
documents.

@item host (string, default: localhost)
This is the native host name of your web server. Sometimes the server has
to send back its own name to the client. It will use this value.
Be aware that you cannot invent such a name.

@item nslookup (boolean, default: false)
If this is true the HTTP server invokes a reverse DNS lookup
for each client connection in order to replace the remote ip address with
the remote host name in the access logfile.

@item ident (boolean, default: false)
If this is true the HTTP server processes identd requests
for each client connection for logging purposes.

@item logfile (string, default: http-access.log)
The location of the access logfile. For each HTTP request a line gets
appended to this file.

@item logformat (string, default: CLF)
The format of the access logfile. There are special placeholders for
different kinds of logging information. The default log format is the
Common Log Format (CLF). It contains a separate line for each request. A 
line is composed of several tokens separated by spaces.
@example
CLF = host ident authuser date request status bytes 
@end example
If a token does not have a value then it is represented by a hyphen (-). 
The meanings and values of these tokens are as follows: 

@table @code
@item %h (host)
The fully-qualified domain name of the client, or its IP number if the name 
is not available.
@item %i (ident)
This is the identity information reported by the client. Not active, so 
we will see a hyphen (-).
@item %u (authuser)
If the request was for an password protected document, then this is the 
userid used in the request. 
@item %t (date)
The date and time of the request, in the following format:
@example
date   = [day/month/year:hour:minute:second zone] 
day    = 2*digit 
month  = 3*letter 
year   = 4*digit 
hour   = 2*digit 
minute = 2*digit 
second = 2*digit 
zone   = (`+' | `-') 4*digit 
@end example
@item %R (request)
The request line from the client, enclosed in double quotes (").
@item %r (referrer)
Which document referred to this document.
@item %a (agent)
What kind of web browser did the remote client use.
@item %c (status)
The three digit status code returned to the client. 
@item %l (bytes)
The number of bytes in the object returned to the client, not including 
any headers. 
@end table
@end table

@node Control Protocol Server, Passthrough Server, HTTP Server, Existing servers
@subsection Control Protocol Server

@subsubsection General description

Serveez implements something like a telnet protocol for 
administrative purposes. You just need to start a telnet session like:
@example
$ telnet www.lkcc.org 42420
@end example
After pressing @key{RET} you will be asked for a password which you
might setup passing Serveez the -P argument. 
@xref{Using Serveez}. The next section describes the interactive commands
available.

@subsubsection Using the Control Protocol

@table @samp
@item help
This command will give you a very short help screen of all available
commands.

@item quit
This command closes the connection to Serveez.

@item restart ident
Restarts the internal ident coserver. This is useful if you just want
to start a new one if the old one died or is otherwise unusable.

@item restart dns
Restarts the internal dns lookup server.

@item restart reverse dns
Restarts the internal reverse dns lookup server.

@item killall
This might be useful if Serveez seems to be unstable but you do not
want to restart it. With @samp{killall} you disconnect all client
network connections except the control protocol connections.

@item kill id NUM
Disconnects a specific connection identified by its ID. These IDs will
be stated when you type @samp{stat con} (see below).

@item stat
General statistics about Serveez. This will show you some useful
information about the computer Serveez is running on and about the
state of Serveez in general.

@item stat coserver
Statistics about all running coserver instances.

@item stat SERVER
This command is for selecting certain server instances to be listed.
SERVER is one of server names you specified in the configuration file.

@item stat id NUM
Show statistics about a specific connection. This will give you all
available information about every connection you specified.
@xref{Writing servers}, for more information about how to provide these
information.

@item stat con
Connection statistics. This will give a list of all socket structures
within Serveez. If you want more detailed information about specific
connections, coservers or servers you need to request these information
with @samp{stat id NUM} or @samp{stat all}.

@item stat all
Server and coserver instance statistics. This command lists all
the information about instantiated servers and coservers.
@xref{Writing servers}, for more information about how to provide these
information.

@item stat cache
HTTP cache statistics. This command produces an output something like the 
following where @samp{File} is the short name of the cache entry, 
@samp{Size} the cache size, @samp{Usage} the amount of connections 
currently using this entry, @samp{Hits} the amount of cache hits, 
@samp{Recent} the cache strategy flag (newer entries have larger numbers) 
and @samp{Ready} is the current state of the cache entry.

@example
File                      Size  Usage  Hits Recent Ready
zlib-1.1.3-20000531.zip  45393      0     0      1 Yes
texinfo.tex             200531      0     0      2 Yes
shayne.txt                2534      0     1      1 Yes

Total : 248458 byte in 3 cache entries
@end example

@item kill cache
Reinitialize the HTTP file cache. Flushes all files from the cache.
@end table

@subsubsection Configuration

There is nothing to be configured yet.

@node Passthrough Server, Mandel Server, Control Protocol Server, Existing servers
@subsection Passthrough Server

@subsubsection General description
The program passthrough server provides basic inetd functionality.
Basically it can accept connections and pass this connection to the standard
input (stdin) and standard output (stdout) handles of programs.  Depending
on the platform (operating system) the user is able to configure different
methods how this can be achieved.

@subsubsection Configuration
This server has different types of configuration options specifying its
behaviour.  Some of them are mandatory and some are optional.  The very
least to configure is the program to be started when a new connection is
made.

@table @code
@item binary (string, no default)
This parameter specifies the program to execute when a new connection
has been accepted.  The parameter is mandatory and must be a fully qualified
file name (including path).

@item directory (string, no default)
This will be the working directory of the executed program.  If you omit 
this parameter the server uses the current directory (the directory is not 
changed).

@item user (string, no default)
If you omit this parameter no user or group will be set for the 
started program.  Otherwise you need to specify this information in the
format @samp{user[.group]}.  If the group is omitted the user's primary
group will be used.

@item argv (string array, no default)
This list of character strings is going to be the program's argument list
(command line).  If the first list item (which is argv[0] and the program's
name) is left blank it defaults to the name specified in the
@code{binary} parameter.

@item do-fork (boolean, default: true)
This flag specifies the method used to pass the connection to the program.
If it is true the server uses the Unix'ish @code{fork()} and @code{exec()}
method.  Otherwise it will pass the data through a unnamed pair of
sockets [ or two pairs of anonymous pipes ].

@item single-threaded (boolean, default: true)
This parameter applies to servers bound to UDP and ICMP port configurations
only.  For programs which process all incoming packets and eventually time 
out, the program is said to be @samp{single-threaded} and should use a true
value here.  If a program gets a packet and can receive further packets, it 
is said to be a @samp{multi-threaded} program, and should use a false value.

@item thread-frequency (integer, default: 40)
The optional @code{thread-frequency} parameter specifies the maximum number
of program instances that may be spawned from the server within an interval
of 60 seconds.
@end table

@node Mandel Server,  , Passthrough Server, Existing servers
@subsection Mandel Server

@html
<pre>[ Example Mandelbrot picture. ]</pre>
<img src="mandel.jpg" border="0" width="320" height="240" 
     alt="Mandelbrot Set">
@end html

@subsubsection General description
The distributed Mandelbrot server is an Internet server completely written
in Guile with the help of the API provided by the underlying Serveez
application.  The reader will not see any occurrence of the networking API
of Guile.

It implements a protocol called @samp{dnc}.  @samp{dnc} - short for 
"Distributed Number Cruncher".  The Mandelbrot server manages the 
computation of a graphic visualization of the Mandelbrot set fractal.  
Each client can connect to the server and ask for something to calculate 
and is meant to send its result back to the server.  Finally the server
produces a bitmap in the XPM format and uses a specified viewer 
application to bring it onto your screen.

@subsubsection Configuration
The server can be setup to manage the calculation of the Mandelbrot set at
various locations (rectangular region in the complex plane), in a specific
pixel resolution and colour depth.  Moreover you can define the name of the
final output file and the viewer application the output file is displayed
with.

@table @code
@item start (string, default: -2.0-1.5i)
Specifies the upper left corner of the final bitmap in the complex plane.

@item end (string, default: +1.1+1.5i)
Specifies the lower right corner of the final bitmap in the complex plane.

@item x-res (integer, default: 320)
The real part pixel resolution.

@item y-res (integer, default: 240)
The imaginary part pixel resolution.

@item colors (integer, default: 256)
Number of maximum colours used in the bitmap.  Also determines the maximum
iteration depth.

@item outfile (string, default: mandel.xpm)
When the Mandel server has managed to calculate the whole bitmap it produces
an output file in the XPM format.  You can specify the name and location of
this output file.

@item viewer (string, default: xv)
Here you can setup your favourite bitmap viewer application.  It should be
able to parse and display the XPM format.
@end table

@node Coserver, Bibliography, Server, Top
@chapter Coserver

@menu
* What are coservers::          The use of coservers in Serveez
* Existing coservers::          What kind of coservers already exist ?
@end menu

@node What are coservers, Existing coservers, Coserver, Coserver
@section What are coservers

If it is necessary to complete blocking tasks in Serveez you have 
to use coservers.  Serveez comes with three useful coservers.

@node Existing coservers,  , What are coservers, Coserver
@section Existing coservers

@subsection Identification (Ident) coserver

The Identification protocol is briefly documented in RFC1413. It
provides a means to determine the identity of a user of a particular 
TCP connection. Given a TCP port number pair, it returns a character 
string which identifies the owner of that connection on the server's
(that is the client's) system.

This is a connection based application on TCP. A server listens for
TCP connections on TCP port 113 (decimal). Once a connection is
established, the server reads a line of data which specifies the
connection of interest. If it exists, the system dependent user
identifier of the connection of interest is sent as the reply. The
server may then either shut down the connection or it may continue to
read/respond to more queries.

The Ident coserver is a client to this kind of service. For
every established network connection you can use this service by calling
the appropriate macro from @file{coserver.h}. But you could also use the
Ident coserver as is without this macro.
The messages from Serveez to this coserver are formatted this way:

@example
Format:
RemoteAddressInDottedDecimals ":" RemotePort ":" LocalPort

Macro:
svz_coserver_ident (sock, MyIdentCallback, sock->id, sock->version);
@end example

In this context @code{sock} is of type @code{svz_socket_t} and 
@code{MyIdentCallback} is something like the following example. Both
of the last two (optional) arguments identify a valid socket structure
and @code{user} can be @code{NULL} if there is no ident daemon running on the 
foreign machine. The last two argument within the above macro will be the 
last two arguments in the callback below. Thus you will know what kind of 
data the invocation of the callback is related to.

@example
Callback:
int
MyIdentCallback (char *user, int id, int version)
@{
  printf ("Identified user: %s\n", user);
  return 0;
@}
@end example

@subsection Domain Name Server (DNS) coserver

The DNS coserver is using @code{gethostbyname()} to translate a given
hostname to the associated IP address. The format of the coserver input
line and the macro from @file{coserver.h} is shown below. The IRC server is
currently using this coserver for resolving its @samp{?-Lines}.
@xref{Existing servers}, for more information. In the example below
@code{realhost} is something like @samp{www.lkcc.org}.

@example
Format:
RemoteHostname

Macro:
svz_coserver_dns (realhost, irc_connect_server, ircserver, NULL);

Callback:
int
irc_connect_server (char *ip, irc_server_t *server)
@{
  printf ("The ip address is: %s\n", ip);
  return 0;
@}
@end example

@subsection Reverse Domain Name Server (reverse DNS) coserver

As easily guessed from the name this coserver is just doing the reverse
as the DNS coserver. It translates a given IP address into a hostname
using @code{gethostbyaddr()}. In the macro the ip address is given
as an @code{unsigned long} in host byte order. The Reverse DNS 
coserver itself takes something like @samp{192.168.2.1}.

@example
Format:
RemoteAddressInDottedDecimals

Macro:
svz_coserver_reverse (addr, MyReverseCallback, sock->id, sock->version);

Callback:
int
MyReverseCallback (char *host, int id, int version)
@{
  printf ("Hostname is: %s\n", host);
  return 0;
@}
@end example


@node Bibliography, License, Coserver, Top
@chapter Bibliography

This section contain some of the documents and resources we read and used
to implement various parts of this package. They appear in no specific
order.

@enumerate
@item 
RFC 760@*
The Internet Protocol
@item 
RFC 1071@*
Computing the Internet Checksum
@item 
RFC 1413@*
Identification Protocol
@item 
RFC 1459@*
Internet Relay Chat Protocol
@item 
RFC 1945@*
Hypertext Transfer Protocol -- HTTP/1.0
@item 
RFC 2068@*
Hypertext Transfer Protocol -- HTTP/1.1
@item 
RFC 2616@*
Hypertext Transfer Protocol -- HTTP/1.1
@item 
RFC 768@*
User Datagram Protocol
@item 
RFC 791@*
Internet Protocol
@item 
RFC 777@*
Internet Control Message Protocol
@item
@uref{http://www.mingw.org/}@*
Home of the MinGW (Minimal GNU for Windows) project
@item 
@uref{http://gnutelladev.wego.com/}@*
The Gnutella Protocol
@item 
@uref{http://www.efnet.org/}@*
The official EFNet site (includes Hybrid IRC server)
@item 
@uref{http://www.sockets.com/}@*
Winsock Development Information
@item 
@uref{http://tangentsoft.net/wskfaq/}@*
Winsock Programmer's FAQ
@end enumerate

@node License,  , Bibliography, Top
@chapter License

GNU General Public License Version 2, June 1991@*

Serveez is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or any later version.

This software is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this package; see the file COPYING.  If not, write to
the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
Boston, MA 02111-1307, USA.

@*
Copyright @copyright{} 2010 Michael Gran <spk121@@yahoo.com>@*
Copyright @copyright{} 1999, 2000, 2001, 2002 Martin Grabmueller <mgrabmue@@cs.tu-berlin.de>@*
Copyright @copyright{} 2000, 2001, 2002 Raimund Jacob <raimi@@lkcc.org>@*
Copyright @copyright{} 2000, 2001, 2002, 2003, 2004 Stefan Jahn <stefan@@lkcc.org>@*

Verbatim copying and distribution of this entire document is
permitted in any medium, provided this notice is preserved.

@contents
@bye
